Getting a weird  ERROR  Error trying to reset password:  [TypeError: validButtons.pop is not a function (it is undefined)] when hitting forgot password from login. It's working fine though. Email still being sent